version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  assignees:
  - textbook
  versioning-strategy: increase
  ignore:
  - dependency-name: webpack
    versions:
    - 5.34.0
  - dependency-name: cypress
    versions:
    - 6.9.1
  - dependency-name: "@babel/core"
    versions:
    - 7.13.14
